In [219]:
import pandas as pd
from keras.src.metrics import accuracy
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [220]:
df = pd.read_csv("./datasets/citrus.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10000 non-null  object
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64
 4   green     10000 non-null  int64
 5   blue      10000 non-null  int64
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB

In [221]:
df.head()

     name  diameter  weight  red  green  blue
0  orange      2.96   86.76  172     85     2
1  orange      3.91   88.05  166     78     3
2  orange      4.42   95.17  156     81     2
3  orange      4.47   95.60  163     81     4
4  orange      4.48   95.76  161     72     9

### Transform category column to numerik

In [222]:
names_pure = df["name"].unique()
names_transform = {value: key for key, value in enumerate(names_pure)}

In [223]:
# WARNING DON'T RERUN MORE THAN ONCE TIME
# df["name"] = df["name"].replace(names_transform) # Deprecated
df["name"] = df["name"].map(names_transform)
df.head()

   name  diameter  weight  red  green  blue
0     0      2.96   86.76  172     85     2
1     0      3.91   88.05  166     78     3
2     0      4.42   95.17  156     81     2
3     0      4.47   95.60  163     81     4
4     0      4.48   95.76  161     72     9

In [224]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10000 non-null  int64
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64
 4   green     10000 non-null  int64
 5   blue      10000 non-null  int64
dtypes: float64(2), int64(4)
memory usage: 468.9 KB

### Split datasets range X = 1-5 y = 5

In [225]:
datasets = df.values

In [226]:
X = datasets[:,1:6] # Take first column up to 5
y = datasets[:,0] # Take sixth column

### Scaler training data (X)

In [227]:
scaler = MinMaxScaler()

X_scaler = scaler.fit_transform(X)
X_scaler

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

### Split to train and test data

In [228]:
X_train, X_test, y_train, y_test = train_test_split(X_scaler, y, train_size=0.3, random_state=42)

### Make model and compile

In [229]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential([
    Dense(32, activation="relu", input_shape=(5,)),
    Dense(16, activation="relu"),
    Dense(8, activation="relu"),
    Dense(1, activation="sigmoid")
])

model.compile(optimizer="sgd", loss="binary_crossentropy", metrics=["accuracy"])

In [230]:
model.fit(X_train, y_train, epochs=200)

Epoch 1/200
94/94 [==============================] - 3s 5ms/step - loss: 0.6493 - accuracy: 0.5883
Epoch 2/200
94/94 [==============================] - 0s 4ms/step - loss: 0.6195 - accuracy: 0.7823
Epoch 3/200
94/94 [==============================] - 0s 4ms/step - loss: 0.5832 - accuracy: 0.8567
Epoch 4/200
94/94 [==============================] - 0s 4ms/step - loss: 0.5360 - accuracy: 0.8823
Epoch 5/200
94/94 [==============================] - 0s 4ms/step - loss: 0.4817 - accuracy: 0.8993
Epoch 6/200
94/94 [==============================] - 0s 4ms/step - loss: 0.4231 - accuracy: 0.9117
Epoch 7/200
94/94 [==============================] - 0s 4ms/step - loss: 0.3657 - accuracy: 0.9167
Epoch 8/200
94/94 [==============================] - 0s 4ms/step - loss: 0.3159 - accuracy: 0.9183
Epoch 9/200
94/94 [==============================] - 0s 4ms/step - loss: 0.2769 - accuracy: 0.9230
Epoch 10/200
94/94 [==============================] - 0s 4ms/step - loss: 0.2491 - accuracy: 0.9253
Epoch 11/200
94/94 [==============================] - 0s 4ms/step - loss: 0.2292 - accuracy: 0.9247
Epoch 12/200
94/94 [==============================] - 0s 4ms/step - loss: 0.2151 - accuracy: 0.9247
Epoch 13/200
94/94 [==============================] - 0s 5ms/step - loss: 0.2063 - accuracy: 0.9273
Epoch 14/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1993 - accuracy: 0.9270
Epoch 15/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1950 - accuracy: 0.9260
Epoch 16/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1915 - accuracy: 0.9267
Epoch 17/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1884 - accuracy: 0.9263
Epoch 18/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1867 - accuracy: 0.9277
Epoch 19/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1859 - accuracy: 0.9250
Epoch 20/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1860 - accuracy: 0.9250
Epoch 21/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1837 - accuracy: 0.9253
Epoch 22/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1842 - accuracy: 0.9250
Epoch 23/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1840 - accuracy: 0.9263
Epoch 24/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1830 - accuracy: 0.9263
Epoch 25/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1827 - accuracy: 0.9267
Epoch 26/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1816 - accuracy: 0.9263
Epoch 27/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1814 - accuracy: 0.9257
Epoch 28/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1819 - accuracy: 0.9243
Epoch 29/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1814 - accuracy: 0.9260
Epoch 30/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1834 - accuracy: 0.9240
Epoch 31/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1823 - accuracy: 0.9260
Epoch 32/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1819 - accuracy: 0.9250
Epoch 33/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1814 - accuracy: 0.9250
Epoch 34/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1804 - accuracy: 0.9287
Epoch 35/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1822 - accuracy: 0.9230
Epoch 36/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1808 - accuracy: 0.9270
Epoch 37/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1814 - accuracy: 0.9253
Epoch 38/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1810 - accuracy: 0.9257
Epoch 39/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1818 - accuracy: 0.9260
Epoch 40/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1810 - accuracy: 0.9257
Epoch 41/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1806 - accuracy: 0.9277
Epoch 42/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1809 - accuracy: 0.9257
Epoch 43/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1811 - accuracy: 0.9247
Epoch 44/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1814 - accuracy: 0.9260
Epoch 45/200
94/94 [==============================] - 0s 5ms/step - loss: 0.1808 - accuracy: 0.9237
Epoch 46/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1809 - accuracy: 0.9257
Epoch 47/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1805 - accuracy: 0.9260
Epoch 48/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1809 - accuracy: 0.9267
Epoch 49/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1815 - accuracy: 0.9240
Epoch 50/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1797 - accuracy: 0.9273
Epoch 51/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1814 - accuracy: 0.9250
Epoch 52/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1796 - accuracy: 0.9273
Epoch 53/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1808 - accuracy: 0.9240
Epoch 54/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1810 - accuracy: 0.9267
Epoch 55/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1789 - accuracy: 0.9260
Epoch 56/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1811 - accuracy: 0.9233
Epoch 57/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1813 - accuracy: 0.9237
Epoch 58/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1817 - accuracy: 0.9240
Epoch 59/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1811 - accuracy: 0.9227
Epoch 60/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1809 - accuracy: 0.9250
Epoch 61/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1813 - accuracy: 0.9253
Epoch 62/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1800 - accuracy: 0.9250
Epoch 63/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1808 - accuracy: 0.9250
Epoch 64/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1797 - accuracy: 0.9250
Epoch 65/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1798 - accuracy: 0.9257
Epoch 66/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1803 - accuracy: 0.9250
Epoch 67/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1807 - accuracy: 0.9260
Epoch 68/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1805 - accuracy: 0.9273
Epoch 69/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1813 - accuracy: 0.9263
Epoch 70/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1810 - accuracy: 0.9257
Epoch 71/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1811 - accuracy: 0.9247
Epoch 72/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1810 - accuracy: 0.9253
Epoch 73/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1802 - accuracy: 0.9253
Epoch 74/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1804 - accuracy: 0.9250
Epoch 75/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1797 - accuracy: 0.9273
Epoch 76/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1804 - accuracy: 0.9253
Epoch 77/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1808 - accuracy: 0.9247
Epoch 78/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1806 - accuracy: 0.9260
Epoch 79/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1794 - accuracy: 0.9290
Epoch 80/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1795 - accuracy: 0.9240
Epoch 81/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1796 - accuracy: 0.9257
Epoch 82/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1808 - accuracy: 0.9263
Epoch 83/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1802 - accuracy: 0.9260
Epoch 84/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1799 - accuracy: 0.9267
Epoch 85/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1804 - accuracy: 0.9247
Epoch 86/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1799 - accuracy: 0.9260
Epoch 87/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1795 - accuracy: 0.9273
Epoch 88/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1807 - accuracy: 0.9243
Epoch 89/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1799 - accuracy: 0.9270
Epoch 90/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1791 - accuracy: 0.9277
Epoch 91/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1803 - accuracy: 0.9267
Epoch 92/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1801 - accuracy: 0.9287
Epoch 93/200
94/94 [==============================] - 0s 5ms/step - loss: 0.1801 - accuracy: 0.9273
Epoch 94/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1793 - accuracy: 0.9267
Epoch 95/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1795 - accuracy: 0.9263
Epoch 96/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1808 - accuracy: 0.9247
Epoch 97/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1796 - accuracy: 0.9253
Epoch 98/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1793 - accuracy: 0.9280
Epoch 99/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1809 - accuracy: 0.9250
Epoch 100/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1796 - accuracy: 0.9280
Epoch 101/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1789 - accuracy: 0.9263
Epoch 102/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1802 - accuracy: 0.9257
Epoch 103/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1794 - accuracy: 0.9273
Epoch 104/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1786 - accuracy: 0.9257
Epoch 105/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1796 - accuracy: 0.9263
Epoch 106/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1796 - accuracy: 0.9270
Epoch 107/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1795 - accuracy: 0.9253
Epoch 108/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1799 - accuracy: 0.9237
Epoch 109/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1806 - accuracy: 0.9257
Epoch 110/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1795 - accuracy: 0.9260
Epoch 111/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1800 - accuracy: 0.9280
Epoch 112/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1794 - accuracy: 0.9277
Epoch 113/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1793 - accuracy: 0.9293
Epoch 114/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1798 - accuracy: 0.9267
Epoch 115/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1790 - accuracy: 0.9260
Epoch 116/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1794 - accuracy: 0.9277
Epoch 117/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1803 - accuracy: 0.9257
Epoch 118/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1798 - accuracy: 0.9277
Epoch 119/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1793 - accuracy: 0.9257
Epoch 120/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1800 - accuracy: 0.9273
Epoch 121/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1801 - accuracy: 0.9257
Epoch 122/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1797 - accuracy: 0.9263
Epoch 123/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1797 - accuracy: 0.9270
Epoch 124/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1796 - accuracy: 0.9273
Epoch 125/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1796 - accuracy: 0.9233
Epoch 126/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1788 - accuracy: 0.9250
Epoch 127/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1798 - accuracy: 0.9263
Epoch 128/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1788 - accuracy: 0.9260
Epoch 129/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1785 - accuracy: 0.9260
Epoch 130/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1785 - accuracy: 0.9260
Epoch 131/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1792 - accuracy: 0.9247
Epoch 132/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1786 - accuracy: 0.9270
Epoch 133/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1792 - accuracy: 0.9273
Epoch 134/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1788 - accuracy: 0.9273
Epoch 135/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1791 - accuracy: 0.9267
Epoch 136/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1790 - accuracy: 0.9260
Epoch 137/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1795 - accuracy: 0.9260
Epoch 138/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1799 - accuracy: 0.9267
Epoch 139/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1794 - accuracy: 0.9240
Epoch 140/200
94/94 [==============================] - 0s 5ms/step - loss: 0.1781 - accuracy: 0.9260
Epoch 141/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1779 - accuracy: 0.9260
Epoch 142/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1790 - accuracy: 0.9267
Epoch 143/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1791 - accuracy: 0.9253
Epoch 144/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1789 - accuracy: 0.9270
Epoch 145/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1778 - accuracy: 0.9277
Epoch 146/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1782 - accuracy: 0.9297
Epoch 147/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1786 - accuracy: 0.9263
Epoch 148/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1795 - accuracy: 0.9270
Epoch 149/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1780 - accuracy: 0.9270
Epoch 150/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1787 - accuracy: 0.9260
Epoch 151/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1790 - accuracy: 0.9277
Epoch 152/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1788 - accuracy: 0.9263
Epoch 153/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1793 - accuracy: 0.9257
Epoch 154/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1784 - accuracy: 0.9240
Epoch 155/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1781 - accuracy: 0.9263
Epoch 156/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1762 - accuracy: 0.9257
Epoch 157/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1783 - accuracy: 0.9260
Epoch 158/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1795 - accuracy: 0.9260
Epoch 159/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1788 - accuracy: 0.9257
Epoch 160/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1780 - accuracy: 0.9243
Epoch 161/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1781 - accuracy: 0.9277
Epoch 162/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1787 - accuracy: 0.9283
Epoch 163/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1782 - accuracy: 0.9267
Epoch 164/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1781 - accuracy: 0.9283
Epoch 165/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1783 - accuracy: 0.9267
Epoch 166/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1790 - accuracy: 0.9283
Epoch 167/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1793 - accuracy: 0.9260
Epoch 168/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1783 - accuracy: 0.9267
Epoch 169/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1786 - accuracy: 0.9280
Epoch 170/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1786 - accuracy: 0.9267
Epoch 171/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1792 - accuracy: 0.9263
Epoch 172/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1787 - accuracy: 0.9243
Epoch 173/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1782 - accuracy: 0.9253
Epoch 174/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1786 - accuracy: 0.9247
Epoch 175/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1779 - accuracy: 0.9260
Epoch 176/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1792 - accuracy: 0.9250
Epoch 177/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1788 - accuracy: 0.9273
Epoch 178/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1787 - accuracy: 0.9243
Epoch 179/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1785 - accuracy: 0.9267
Epoch 180/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1789 - accuracy: 0.9277
Epoch 181/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1778 - accuracy: 0.9270
Epoch 182/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1780 - accuracy: 0.9247
Epoch 183/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1782 - accuracy: 0.9253
Epoch 184/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1777 - accuracy: 0.9257
Epoch 185/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1776 - accuracy: 0.9273
Epoch 186/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1779 - accuracy: 0.9247
Epoch 187/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1780 - accuracy: 0.9283
Epoch 188/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1780 - accuracy: 0.9287
Epoch 189/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1784 - accuracy: 0.9293
Epoch 190/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1781 - accuracy: 0.9263
Epoch 191/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1766 - accuracy: 0.9280
Epoch 192/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1790 - accuracy: 0.9267
Epoch 193/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1775 - accuracy: 0.9290
Epoch 194/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1769 - accuracy: 0.9260
Epoch 195/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1780 - accuracy: 0.9270
Epoch 196/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1765 - accuracy: 0.9277
Epoch 197/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1785 - accuracy: 0.9260
Epoch 198/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1774 - accuracy: 0.9270
Epoch 199/200
94/94 [==============================] - 0s 4ms/step - loss: 0.1784 - accuracy: 0.9260

### Evaluate model

In [231]:
model.evaluate(X_test, y_test, batch_size=1)

7000/7000 [==============================] - 24s 3ms/step - loss: 0.1789 - accuracy: 0.9289

[0.1789085865020752, 0.928857147693634]

In [232]:
one_of_data_train = df.loc[9998].drop("name").values.reshape(1, -1)

pred = model.predict([one_of_data_train])
result = int(pred[0][0])

names_reversed = dict(map(reversed, names_transform.items()))
print(names_reversed[result])

1/1 [==============================] - 0s 182ms/step
grapefruit

In [233]:
names_reversed

{0: 'orange', 1: 'grapefruit'}