### Case Folding

In [1]:
real_text = "Hi my name is Verdi, I from Indonesia East Java"

lower_text = real_text.lower()

print(f"Real text: \n {real_text}")
print(f"Text to lower case: \n {lower_text}")

Real text:
 Hi my name is Verdi, I from Indonesia East Java
Text to lower case:
 hi my name is verdi, i from indonesia east java

### Removal Special Characters / Noise Removal

In [2]:
import string

dirty_text = "Hey @John! The price of this product is $50.99, and a 20% discount is only valid until 02/14/2025. Don’t forget to visit www.example.com for more info! #Promo      "
print("Dirty text: \n", dirty_text)

Dirty text:
 Hey @John! The price of this product is $50.99, and a 20% discount is only valid until 02/14/2025. Don’t forget to visit www.example.com for more info! #Promo

### General Removal

In [3]:
def remove_number(text: str) -> str:
    tm = ''.join([char for char in text if not char.isdigit()])
    return tm

def remove_symbol(text: str)-> str:
    punc_set = set(string.punctuation)
    tm = ''.join([char for char in text if char not in punc_set])
    return tm

def remove_end_start_space(text: str)-> str:
    return text.strip()

### Stopwords Removal
With __NLTK__

In [4]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download("stopwords")
nltk.download("punkt_tab") # for tokenization

def stopwords_nltk(text: str, language: str = "english")-> str:
    word_tokens = word_tokenize(text)
    stopwords_lang = set(stopwords.words(language))
    filtered_words = [word for word in word_tokens if word.lower() not in stopwords_lang]
    return ' '.join(filtered_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [5]:
stopwords_nltk("Perekonomian Indonesia sedang dalam pertumbuhan yang membanggakan.", "indonesian")

'Perekonomian Indonesia pertumbuhan membanggakan .'

With __Sastrawi__ <br>
Is a library for NLP Indonesian Language.

In [6]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# Initialization StopWordRemover object from Sastrawi
factory = StopWordRemoverFactory()

def stopwords_sastrawi(text: str)-> str:
    stopwords_lang = factory.get_stop_words()
    word_tokens = word_tokenize(text)
    filtered_words = [word for word in word_tokens if word.lower() not in stopwords_lang]
    return ' '.join(filtered_words)

In [7]:
stopwords_sastrawi("Perekonomian Indonesia sedang dalam pertumbuhan yang membanggakan.")

'Perekonomian Indonesia sedang pertumbuhan membanggakan .'

### Tokenization
__Word Tokenization__ <br>
Split text by white space

In [8]:
example_tokenize_text = "Ekonomi Indonesia sedang tidak baik-baik saja! karena ada pergantian mentri bejat yang tidak tidak bertanggung jawab."

word_tokens = word_tokenize(example_tokenize_text)
print(word_tokens)

['Ekonomi', 'Indonesia', 'sedang', 'tidak', 'baik-baik', 'saja', '!', 'karena', 'ada', 'pergantian', 'mentri', 'bejat', 'yang', 'tidak', 'tidak', 'bertanggung', 'jawab', '.']

__Sentence Tokenization__ <br>
Split text by punctuation

In [9]:
from nltk.tokenize import sent_tokenize

sentence_tokens = sent_tokenize(example_tokenize_text)
print(sentence_tokens)

['Ekonomi Indonesia sedang tidak baik-baik saja!', 'karena ada pergantian mentri bejat yang tidak tidak bertanggung jawab.']

__Phrase Tokenization__ <br>
Split text by phrases or units more than big singular words.

In [10]:
from nltk.tokenize import TreebankWordTokenizer

three_bank_words = TreebankWordTokenizer()
phrase_tokenization = three_bank_words.tokenize(example_tokenize_text)
print(phrase_tokenization)

# Or you can just use text.split(",")

['Ekonomi', 'Indonesia', 'sedang', 'tidak', 'baik-baik', 'saja', '!', 'karena', 'ada', 'pergantian', 'mentri', 'bejat', 'yang', 'tidak', 'tidak', 'bertanggung', 'jawab', '.']

__Rule-Based Tokenization__ <br>
Use linguistics rule or processing text rule to split text into tokens.
Example special tokenization for URL, email, phone number, coordinate, etc

In [11]:
import re

pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}|https?://\S+|\w+(?:-\w+)*|\d+'

rule_based_tokens = re.findall(pattern, "Halo! Silakan kirim email ke support@example.com untuk bantuan lebih lanjut. Kunjungi juga website kami di https://www.example.com/faq . Proyek ini adalah proyek jangka-panjang yang membutuhkan bahan-bahan tambahan. Harga produk: $45.99.")

print(rule_based_tokens)

['Halo', 'Silakan', 'kirim', 'email', 'ke', 'support@example.com', 'untuk', 'bantuan', 'lebih', 'lanjut', 'Kunjungi', 'juga', 'website', 'kami', 'di', 'https://www.example.com/faq', 'Proyek', 'ini', 'adalah', 'proyek', 'jangka-panjang', 'yang', 'membutuhkan', 'bahan-bahan', 'tambahan', 'Harga', 'produk', '45', '99']

__Combine Rule-based and word tokenization__

In [12]:
# Pattern to catch URL, email, and coordinate
pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}|https?://\S+|[-+]?\d*\.\d+,\s*[-+]?\d*\.\d+'

text = "Email kami support@example.com, kunjungi https://www.example.com, dan koordinat lokasi: 37.7749,-122.4194."

special_token = re.findall(pattern, text)
cleaned_text = re.sub(pattern, '', text)
word_tokens = word_tokenize(cleaned_text)

combine = special_token + word_tokens
print(combine)

['support@example.com', 'https://www.example.com,', '37.7749,-122.4194', 'Email', 'kami', ',', 'kunjungi', 'dan', 'koordinat', 'lokasi', ':', '.']

### Stemming
Is a process in NLP to simplify words into original form by remove word set.

In [13]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

def stemming_words(words: list[str])-> list[str]:
    return [stemmer.stem(word) for word in words]

words = ["running", "runs", "runner", "ran", "easily", "fairness", "better", "best", "cats", "rocks"]

result_stemming = stemming_words(words)

# Show different
import pandas as pd

one = pd.DataFrame(words, columns=["Words"])
two = pd.DataFrame(result_stemming, columns=["Result Stemming"])
pd.concat([one, two], axis=1)

      Words Result Stemming
0   running             run
1      runs             run
2    runner          runner
3       ran             ran
4    easily          easili
5  fairness            fair
6    better          better
7      best            best
8      cats             cat
9     rocks            rock

__Stemming with Sastrawi__

In [14]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

stem_factory = StemmerFactory()
stemmer = stem_factory.create_stemmer()

words = "Perekonomian Indonesia sedang berkembang pesat".split(" ")

results = [stemmer.stem(word) for word in words]

# Show different
one = pd.DataFrame(words, columns=["Words"])
two = pd.DataFrame(results, columns=["Words Stemmed"])
pd.concat([one, two], axis=1)

          Words Words Stemmed
0  Perekonomian       ekonomi
1     Indonesia     indonesia
2        sedang        sedang
3    berkembang       kembang
4         pesat         pesat

### Lemmatization
Lemmatization is a technique in text processing to convert words to their base form, called lemmas (or lema). The goal is to unify words with the same root so that they can be represented through a single base form that correctly represents the meaning of the word.

In [15]:
from nltk.stem import WordNetLemmatizer

nltk.download("wordnet")

lemmatizer = WordNetLemmatizer()

words = ["running","flies","better","children","went","bigger","cats","talked","leaves","buying"]

def lemmatization_words(words: list[str])-> list[str]:
    return [lemmatizer.lemmatize(word.lower()) for word in words]

results = lemmatization_words(words)

one = pd.DataFrame(words, columns=["Original"])
two = pd.DataFrame(results, columns=["Result"])

pd.concat([one, two], axis=1)

# The results are just noun to conversed

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

   Original   Result
0   running  running
1     flies      fly
2    better   better
3  children    child
4      went     went
5    bigger   bigger
6      cats      cat
7    talked   talked
8    leaves     leaf
9    buying   buying

__Lemmatization with POS tagging__

In [19]:
from nltk import pos_tag
from nltk.corpus import wordnet

nltk.download("averaged_perceptron_tagger_eng")
nltk.download("omw-1.4")

def get_word_pos(tag: str):
    if tag.startswith("J"):
        return wordnet.ADJ
    elif tag.startswith("N"):
        return wordnet.NOUN
    elif tag.startswith("R"):
        return wordnet.ADV
    elif tag.startswith("V"):
        return wordnet.VERB
    else:
        return wordnet.NOUN

def lemmatization_with_pos(words: list[str])->list[str]:
    pos_tags = pos_tag(words)
    return [lemmatizer.lemmatize(word.lower(), get_word_pos(tag)) for word, tag in pos_tags]

results = lemmatization_with_pos(words)

# Preview
one = pd.DataFrame(words, columns=["Before"])
two = pd.DataFrame(results, columns=["After"])

pd.concat([one, two], axis=1)

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

     Before  After
0   running    run
1     flies    fly
2    better   well
3  children  child
4      went     go
5    bigger    big
6      cats    cat
7    talked   talk
8    leaves   leaf
9    buying    buy

The conclusion is Lemmatization is powerful than Stemming, because stemming is just remove start and end of word set, Lemmatization is more careful because it takes into account the morphological rules of the language